# Generated by Django 5.1.1 on 2024-10-21 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0015_customuser_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='company_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofilemodel',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='resume',
            field=models.FileField(null=True, upload_to='Media/Resume'),
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('openings', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('skills_required', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.jobposting')),
            ],
        ),
    ]
