# Generated by Django 5.1.1 on 2024-10-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_recruiterprofilemodel_company_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='seekerprofilemodel',
            name='skills',
        ),
        migrations.AddField(
            model_name='seekerprofilemodel',
            name='skills',
            field=models.ManyToManyField(null=True, to='myApp.skillmodel'),
        ),
    ]
