# Generated by Django 5.1.1 on 2024-10-21 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0017_skillmodel_remove_seekerprofilemodel_skills_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='JobApplicationModel',
        ),
    ]
