# Generated by Django 5.1.1 on 2024-10-21 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0018_rename_application_jobapplicationmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobPosting',
            new_name='JobModel',
        ),
    ]
