# Generated by Django 5.1.1 on 2024-10-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_rename_jobposting_jobmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='skills_required',
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='jobs_model', to='myApp.skillmodel'),
        ),
    ]
