# Generated by Django 5.1.1 on 2024-10-21 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0020_remove_jobmodel_skills_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='Job_Image',
            field=models.ImageField(null=True, upload_to='Media/Job_Image'),
        ),
    ]
