# Generated by Django 5.1.1 on 2024-10-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0021_jobmodel_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='Media/Resumes'),
        ),
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='skills_required',
            field=models.ManyToManyField(blank=True, related_name='job_applications', to='myApp.skillmodel'),
        ),
    ]
